scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus-server:9090"]

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
